-- Separate tables: this does not modify the existing Phase-1 GSC collector tables.
create table if not exists public.trend_runs (
  id bigint generated by default as identity primary key,
  run_date date not null unique,
  started_at timestamptz not null default now(),
  completed_at timestamptz,
  candidate_count integer default 0,
  qualified_count integer default 0,
  top5 jsonb default '[]'::jsonb,
  selected jsonb default '[]'::jsonb,
  status text not null default 'started'
);

create table if not exists public.trend_candidates (
  id bigint generated by default as identity primary key,
  candidate_key text not null unique,
  run_date date not null,
  rank integer,
  query text not null,
  source text,
  approx_traffic bigint,
  growth_signal numeric,
  niche_relevance numeric,
  business_intent numeric,
  opportunity_score numeric,
  publication_score numeric,
  decision jsonb,
  research jsonb,
  status text not null default 'researched',
  created_at timestamptz not null default now()
);
create index if not exists trend_candidates_run_date_idx on public.trend_candidates(run_date desc);
create index if not exists trend_candidates_query_idx on public.trend_candidates using gin (to_tsvector('english', query));

create table if not exists public.trend_publications (
  id bigint generated by default as identity primary key,
  candidate_key text,
  query text not null,
  action text not null check (action in ('CREATE','UPDATE','EXPAND')),
  url text not null,
  file_path text,
  publication_score numeric,
  quality_score numeric,
  status text not null check (status in ('draft','published','updated','failed')),
  issues jsonb default '[]'::jsonb,
  published_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists trend_publications_url_idx on public.trend_publications(url);
create index if not exists trend_publications_date_idx on public.trend_publications(published_at desc);

create table if not exists public.trend_index_checks (
  id bigint generated by default as identity primary key,
  publication_id bigint references public.trend_publications(id) on delete cascade,
  url text not null,
  checked_at timestamptz not null default now(),
  age_days integer,
  verdict text,
  coverage_state text,
  robots_txt_state text,
  indexing_state text,
  last_crawl_time timestamptz,
  google_canonical text,
  user_canonical text,
  live_check jsonb
);
create index if not exists trend_index_checks_url_idx on public.trend_index_checks(url, checked_at desc);

-- Keep automation data private. The server-side secret/service-role key bypasses RLS.
alter table public.trend_runs enable row level security;
alter table public.trend_candidates enable row level security;
alter table public.trend_publications enable row level security;
alter table public.trend_index_checks enable row level security;
